<?php

/**
 * @file
 * Contains datetime_multiselect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datetime_multiselect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the datetime_multiselect module.
    case 'help.page.datetime_multiselect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Calendar Multi-select') . '</p>';
      return $output;

    default:
  }
}