enabled_default: 0
default_challenge: recaptcha/reCAPTCHA
description: 'Cette question sert à tester si vous êtes ou non un visiteur humain et à empêcher les soumissions de spam automatisées.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: _UaIWu0_ZD3lUs97wlFC2Koi-o7Bex69Xr9q36nJtkY
langcode: fr
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
