api_key: f75ab6d01bdb8708fb2b15c269bc8328-us11
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
langcode: fr
enable_connected: false
connected_id: null
connected_paths: null
api_timeout: 10
