moneris:
  profile_id: "https://api.aeroportdequebec.com: htOABAZJ7D4KTAO\r\nhttps://www.aeroportdequebec.com: htQZVVI122I9MNQ\r\nhttp://api.aeroportdequebec.com: ht98P83A3KVVB11\r\nhttp://www.aeroportdequebec.com: htQEUE9URZ7VAAN\r\nhttps://yqb.prod.acquia-sites.com: htMHZY9EZFI6UBB"
  store_id: monca88072
  api_key: 8IFyA7j0jSoXwFpMmc1G
  api_url: 'https://www3.moneris.com'
  environment: live
