site_key: 6LdFs-0bAAAAAKQKM1UkVDeYO8mgs4rg-B68GwPX
secret_key: 6LdFs-0bAAAAAAHn7xgJzNWDo90SU2XiEnAB8pXV
verify_hostname: true
default_challenge: recaptcha/reCAPTCHA
error_message: 'Échec de la vérification de l''antibot.'
cacheable: false
_core:
  default_config_hash: jv0PKCJEOq2bOwY9RspuPZCf67ifVJ4tfTk-BfZMw8k
langcode: fr
