favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://yqb.dev/themes/yqb/favicon.ico'
  use_default: true
region_wells:
  sub_navigation: ''
  top: ''
  sidebar_second: ''
  bottom: ''
  sub_footer: ''
breadcrumb_home: 1
fluid_container: 1
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  yqb: 8000
langcode: fr
