list_id: fbcc0156a1
template_id: '356849'
from_name: 'Aéroport de Québec inc.'
from_email: rh@aeroportdequebec.com
_core:
  default_config_hash: b5pWg8vq2IHkwZCq3xNN_S4MPxb0bmG63vUmeqqXnNI
langcode: fr
audience_tag: '8121169'
