#!/bin/bash

# TODO: How to manage the fact that this requires MySQL more elegantly
docker exec -u root -i yqb_php-fpm apk add mysql-client &> /dev/null
docker exec -u app -i yqb_php-fpm /app/vendor/drush/drush/drush "$@"