version: "2"

services:
  web:
    build: ./nginx
    ports:
      - "8989:80"
    volumes:
      - ../..:/site
      - ./nginx/conf-nginx.conf:/etc/nginx/nginx.conf
    links:
      - php

  php:
    build: ./php
    volumes:
      - ../..:/site
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  database:
    image: mariadb:10
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ../bd:/bd
    ports:
      - "34306:3306"
    restart: always
