<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\yqb_payments\Entity\YqbPaymentEntity;
use Drupal\yqb_payments\Form\CheckoutForm;

/**
 * Implements hook_entity_base_field_info().
 */
function yqb_payments_entity_base_field_info(EntityTypeInterface $entity_type)
{
  if ($entity_type->id() == 'yqb_payment') {
    return YqbPaymentEntity::getConfigurableFields();
  }
}

/**
 * Implements hook_theme().
 */
function yqb_payments_theme($existing, $type, $theme, $path)
{
  return [
    'yqb_payments_checkout' => [
      'variables' => [
        'customer' => false
      ]
    ],
    'yqb_payments_success' => [
      'variables' => [
        'customer' => false,
        'receipt' => false
      ]
    ]
  ];
}

function yqb_payments_preprocess_yqb_payments_checkout(&$variables)
{
  $variables['checkout_form'] = Drupal::formBuilder()->getForm(CheckoutForm::class);
}
