name: Configuration development module
type: module
description: 'Helps developers work with configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_devel.settings

# Information added by Drupal.org packaging script on 2016-06-21
version: '8.x-1.0-rc1+8-dev'
core: '8.x'
project: 'config_devel'
datestamp: 1466497440
