<?php

/**
 * @file
 * Contains twilio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twilio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twilio module.
    case 'help.page.twilio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twilio') . '</p>';
      return $output;

    default:
  }

  return '';
}

/**
 * Implements hook_theme().
 */
function twilio_theme() {
  $theme = [];

  return $theme;
}
