yqb_parking_booker.settings:
  type: config_object
  label: 'Parking Booker settings'
  mapping:
    submit_button:
      type: text
      label: 'Libellé du bouton'
    disabled:
      type: boolean
      label: 'Disable Parking Booker Form'
    disabled_text:
      type: text
      label: 'Disabled message'
