<?php

/**
 * @file
 * Contains advam.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function advam_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advam module.
    case 'help.page.advam':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Advam') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function advam_theme() {
  $theme = [];

  return $theme;
}
