<?php

/**
 * Implements hook_cron().
 */
function yqb_mailchimp_cron() {
  $config = \Drupal::configFactory()
                   ->getEditable('yqb_mailchimp.settings');

  $interval = $config->get('interval');
  $interval = !empty($interval) ? $interval : 120;

  $nextExecution = Drupal::state()->get('yqb_mailchimp.next_execution');
  $nextExecution = !empty($nextExecution) ? $nextExecution : 0;

  if (\Drupal::time()->getRequestTime() >= $nextExecution) {
    /** @var \Drupal\yqb_mailchimp\Career $career */
    $career = Drupal::classResolver(\Drupal\yqb_mailchimp\Career::class);
    $nodes = $career->findAvailableCareerAlerts();

    foreach ($nodes as $node) {
      $career->sendCareerAlert($node);
    }

    \Drupal::state()->set(
      'yqb_mailchimp.next_execution',
      \Drupal::time()->getRequestTime() + $interval
    );
  }
}


/**
 * Implements hook_theme().
 */
function yqb_mailchimp_theme($existing, $type, $theme, $path) {
  return [
    'yqb_mailchimp_template' => [
      'variables' => [
        'node' => NULL,
        'title' => '',
        'type' => '',
        'department' => '',
        'location' => '',
        'summary' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function yqb_mailchimp_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (preg_match('/^mailchimp_signup_subscribe_page/i', $form_id)) {
    $form['#attached']['library'][] = 'yqb_mailchimp/yqb_mailchimp';
  }
}

/**
 * Gets an array of list categories for a given list ID.
 *
 * @param int $list_id
 *   The list ID.
 * @param string $type
 *   The segment type to get. "static" or "saved".
 *
 * @return array
 *   Array of Mailchimp list categoties (Group, interests, topics, etc).
 */
function yqb_mailchimp_campaign_get_list_interests($list_id, $type) {
  /* @var \Mailchimp\MailchimpLists $mcapi */
  $mcapi = mailchimp_get_api_object('MailchimpLists');

  $parameters = [
    'type' => $type,
    'count' => 500,
  ];

  $categories = [];
  try {
    $response = $mcapi->getInterestCategories($list_id, $parameters);

    foreach ($response->categories as $cat) {
      $resp = $mcapi->getInterests($list_id, $cat->id, $parameters);

      $categories[] = array('title' => $cat->title,
                            'list_id' => $cat->list_id,
                            'type' => $cat->type,
                            'category_id' => $resp->category_id,
                            'interests' => $resp->interests);
    }
  }
  catch (\Exception $e) {
    \Drupal::messenger()->addError($e->getMessage());
    \Drupal::logger('mailchimp_campaign')->error('An error occurred getting list segments for list ID {list_id}: {message} ', [
      'list_id' => $list_id,
      'message' => $e->getMessage(),
    ]);

    return NULL;
  }

  return $categories;
}