yqb_alert.settings:
  type: mapping
#  label: 'Advam settings'
#  mapping:
#    advam:
#      type: mapping
#      mapping:
#        api_url:
#          type: text
#          label: 'API URL:'
#        api_key:
#          type: text
#          label: 'API key:'
#        airport_code:
#          type: text
#          label: 'Airport code:'
#        use_legacy:
#          type: boolean
#          label: 'Use the legacy booking platform:'
